---
title: "DMX_Linkages_Data_Visualizations"
author: "Rachael Blake"
date: "January 27, 2016"
output: html_document
---

# Data Visualizations for DMX Linkages

Plot 1: Heatmap of all datasets we have in hand to date

```{r, echo=FALSE}

# load necessary packages
library(httr)
library(plyr)
library(dplyr)
library(XML)
library(curl)
library(rvest)
library(tidyr)
library(stringr)


# call the data assembly script
source("commPracticeDataFormat.R")
#head(CoPrct) ; str(CoPrct)


```


```{r, echo=FALSE}
# load smore more packages that were creating conflicts with reading in the data
library(reshape)
library(ggplot2)
library(scales)

```


```{r}

# plot data presence in time for each variable
melt_CoPr <- melt(CoPrct, id.vars="Year", variable_name="Data_Set")

melt_CoPr <- mutate(melt_CoPr, Bin_Value = ifelse((is.na(value)),'0',
                                           ifelse((!is.na(value)),'1',"")))


p <- ggplot(data=melt_CoPr, aes(x=Data_Set, y=Year)) + 
            geom_tile(aes(fill = Bin_Value), colour = "white") +
            scale_fill_manual(values=c("0"="white", "1"="red"), guide=FALSE) +
            scale_y_reverse() + 
            theme(axis.text.x = element_text(angle=70, vjust=1, hjust=1, color="black", size=15),
                  axis.text.y = element_text(color="black", size=15),
                  axis.title  = element_text(face="bold", size=20))
p


```



