---
title: ''
author: "Rachael Blake"
date: "January 27, 2016"
output: pdf_document
---

# Random Forest Analysis Exploration for DMX Linkages

```{r, echo=FALSE, include=FALSE}

# load necessary packages
library(randomForest) ; library(plyr) ; library(dplyr)



# call the data assembly script
source("commPracticeDataFormat.R")
#head(CoPrct)

# filter data for complete cases
#CPD4 <- CPD %>%
#        select(which(colMeans(is.na(.)) < 0.5)) %>%
#        filter(complete.cases(.))

```


```{r, echo=FALSE}
# Some data transformations

CPD <- CoPrct %>%
       mutate(log_WTemp_C_AnnMn = log(WTemp_C_AnnMn),
              log_SwdLineMayEuphausiids = log(SewardLineMayEuphausiids),
              log_SwdLineMayCopepods = log(SewardLineMayCopepods),
              log_Poll_Age1_recruits_millions = log(Poll_Age1_recruits_millions),
              log_Pink_Shrimp = log(Pink_Shrimp),
              log_hlbt_pounds = log(hlbt_pounds)
              )

```


```{r, echo=FALSE}
# Define some functions

# Important variables are greater than the absolute value of the most negative
# importance value.
Imp_Var <- function(rf_obj){
           a <- data.frame(rf_obj$importance)  
           b <- min(a[,1])  # smallest value
           c <- abs(b)  # absolute value of smallest value
           d <- a$X.IncMSE[a$X.IncMSE>c]  # numbers great than absolute value of smallest value
           return(d)
           }


```


```{r, fig.height=6, fig.width=8}
###
# Pink Salmon
CPD_Pink <- CPD %>% 
            select(PDO_anul_mn,NPGO_anul_mn,#WndSp_m_s_AnnMn,WndDir_degT_AnnMn,
                   WTemp_C_AnnMn,AnnChl,SewardLineMayEuphausiids,SewardLineMayCopepods,
                   goaPinkCatchNum,PWS_WildPinkSalmon_SSB_ModelOutput,ArrAdult,
                   Poll_Yr3plus_TtlBmss_1000Tons) %>%
            filter(complete.cases(.))
goaPink <- randomForest(goaPinkCatchNum ~., data=CPD_Pink, importance=T, 
                        do.trace=1000, ntree=5000)
print(goaPink)
#plot(goaPink)
varImpPlot(goaPink)
goaPink$importance

```

```{r,fig.height=6, fig.width=8}

# Arrowtooth
CPD_Arrow <- CPD %>% 
             select(PDO_anul_mn,NPGO_anul_mn,#WndSp_m_s_AnnMn,WndDir_degT_AnnMn,
                    WTemp_C_AnnMn,AnnChl,SewardLineMayEuphausiids,Poll_Age1_recruits_millions,
                    ArrAdult,arth_tons,arth_real_rev,arth_vessels,arth_processors,arth_real_price) %>%
             filter(complete.cases(.))
arrow <- randomForest(ArrAdult ~., data=CPD_Arrow, importance=T, do.trace=1000, ntree=5000)
print(arrow)
#plot(arrow)
varImpPlot(arrow)
arrow$importance

```


```{r,fig.height=6, fig.width=8}

# Pollock Adults
CPD_Poll <- CPD %>% 
            select(PDO_anul_mn,NPGO_anul_mn,#WndSp_m_s_AnnMn,WndDir_degT_AnnMn,
                   WTemp_C_AnnMn,AnnChl,EKE_ann_max_mean,SewardLineMayEuphausiids,
                   SewardLineMayCopepods,Pink_Shrimp,Poll_Age1_recruits_millions,
                   Poll_Yr3plus_TtlBmss_1000Tons,ArrAdult, PCod_female_Bmss_t,hlbt_pounds,
                   plck_tons,plck_real_rev,plck_vessels,plck_processors) %>%
            filter(complete.cases(.))
poll_a <- randomForest(Poll_Yr3plus_TtlBmss_1000Tons ~., data=CPD_Poll, importance=T, do.trace=1000, ntree=5000)
print(poll_a)
#plot(poll_a)
varImpPlot(poll_a)
poll_a$importance

```

```{r,fig.height=6, fig.width=8}

# Pollock Juvenile
CPD_JPoll <- CPD %>%
             select(PDO_anul_mn,NPGO_anul_mn,#WndSp_m_s_AnnMn,WndDir_degT_AnnMn,
                    WTemp_C_AnnMn,AnnChl, EKE_ann_max_mean,SewardLineMayEuphausiids,
                    SewardLineMayCopepods,Poll_Age1_recruits_millions,
                    Poll_Yr3plus_TtlBmss_1000Tons,ArrAdult) %>%
             filter(complete.cases(.))
poll_j <- randomForest(Poll_Age1_recruits_millions ~., data=CPD_JPoll, importance=T, do.trace=1000, ntree=5000)
print(poll_j)
#plot(poll_j)
varImpPlot(poll_j)
poll_j$importance

```

```{r,fig.height=6, fig.width=8}

# Halibut
CPD_Hal <- CPD %>% 
           select(PDO_anul_mn,NPGO_anul_mn,#WndSp_m_s_AnnMn,WndDir_degT_AnnMn,
                  WTemp_C_AnnMn,AnnChl,Poll_Yr3plus_TtlBmss_1000Tons, Poll_Age1_recruits_millions,
                  TotTCrab,Pink_Shrimp,hlbt_pounds,hlbt_real_rev,hlbt_vessels,hlbt_processors) %>%
           filter(complete.cases(.))
hlbt_lbs <- randomForest(hlbt_pounds ~., data=CPD_Hal, importance=T, do.trace=1000, ntree=5000)
print(hlbt_lbs)
#plot(hlbt_lbs)
varImpPlot(hlbt_lbs)
hlbt_lbs$importance

```

